# Generated by Django 3.2.9 on 2021-11-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catchy', '0002_auto_20211126_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='catchy.category'),
        ),
    ]
